server:
  port: 9098
  
spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
  application:
    name: Redis-Cache-Refresh

  output:
    ansi:
        enabled: DETECT
        
  datasource:
    url: jdbc:mysql://localhost:3306/dbviews
    username: root
    password: password
    dbcp2:
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

#BASE.URL: http://45.114.48.150:8081/api/fleet/getvehicle
BASE.URL: http://localhost:8081/api/fleet/getvehicle

logging:
  level:
    org.springframework.web: ERROR
    com.asiczen: ERROR
  file:
    name: /home/lora/scorpious/scorpious-logs/redis-mysql-sync.log
    max-size: 10 MB          